import { Theme } from "@/types";

export const DEFAULT_THEMES: Theme[] = [
  {
    id: "sakura",
    name: "Sakura",
    thumbnailUrl: "/images/themes/sakura-thumb.jpg",
    isPremium: false,
    isActive: true,
    config: {
      primaryColor: "#F4A7B9",
      secondaryColor: "#FDF2F8",
      accentColor: "#E8748A",
      backgroundColor: "#FDF8F0",
      textColor: "#4A2C2A",
      fontHeading: "Cormorant Garamond",
      fontBody: "Lato",
      fontScript: "Great Vibes",
      ornamentStyle: "floral",
    },
  },
  {
    id: "ivory-elegance",
    name: "Ivory Elegance",
    thumbnailUrl: "/images/themes/ivory-thumb.jpg",
    isPremium: false,
    isActive: true,
    config: {
      primaryColor: "#C9A96E",
      secondaryColor: "#FDF8F0",
      accentColor: "#8B6914",
      backgroundColor: "#FAFAF7",
      textColor: "#2D2D2D",
      fontHeading: "Cormorant Garamond",
      fontBody: "Lato",
      fontScript: "Great Vibes",
      ornamentStyle: "minimal",
    },
  },
  {
    id: "botanical",
    name: "Botanical",
    thumbnailUrl: "/images/themes/botanical-thumb.jpg",
    isPremium: false,
    isActive: true,
    config: {
      primaryColor: "#84A98C",
      secondaryColor: "#F0F4F0",
      accentColor: "#52796F",
      backgroundColor: "#F8FAF8",
      textColor: "#2F3E46",
      fontHeading: "Cormorant Garamond",
      fontBody: "Lato",
      fontScript: "Great Vibes",
      ornamentStyle: "floral",
    },
  },
  {
    id: "celestial-dark",
    name: "Celestial Dark",
    thumbnailUrl: "/images/themes/celestial-thumb.jpg",
    isPremium: true,
    isActive: true,
    config: {
      primaryColor: "#F4D03F",
      secondaryColor: "#1E3A5F",
      accentColor: "#C9A96E",
      backgroundColor: "#0D1B2A",
      textColor: "#F0F0F0",
      fontHeading: "Cormorant Garamond",
      fontBody: "Lato",
      fontScript: "Great Vibes",
      ornamentStyle: "celestial",
    },
  },
  {
    id: "batik-heritage",
    name: "Batik Heritage",
    thumbnailUrl: "/images/themes/batik-thumb.jpg",
    isPremium: true,
    isActive: true,
    config: {
      primaryColor: "#8B4513",
      secondaryColor: "#FDF0E8",
      accentColor: "#D2691E",
      backgroundColor: "#FDF5EC",
      textColor: "#3D1C02",
      fontHeading: "Cormorant Garamond",
      fontBody: "Lato",
      fontScript: "Great Vibes",
      ornamentStyle: "batik",
    },
  },
];
